name: adamw
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.9, 0.999]

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${trainer.max_epochs}
  eta_min: 1e-6
